DjangoBlog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from DjangoBlog.sitemap import StaticViewSitemap, ArticleSiteMap, CategorySiteMap, TagSiteMap, UserSiteMap
from DjangoBlog.feeds import DjangoBlogFeed
from django.views.decorators.cache import cache_page
from django.conf import settings
from django.conf.urls.static import static   #注意导包,多个static 
from DjangoBlog.admin_site import admin_site
from django.urls import include, path

sitemaps = {

    'blog': ArticleSiteMap,
    'Category': CategorySiteMap,
    'Tag': TagSiteMap,
    'User': UserSiteMap,
    'static': StaticViewSitemap
}

handler404 = 'blog.views.page_not_found_view'
handler500 = 'blog.views.server_error_view'
handle403 = 'blog.views.permission_denied_view'
urlpatterns = [
                  url(r'^admin/', admin_site.urls),
                  url(r'', include('blog.urls', namespace='blog')),
                  url(r'mdeditor/', include('mdeditor.urls')),
                  url(r'', include('comments.urls', namespace='comment')),
                  url(r'', include('accounts.urls', namespace='account')),
                  url(r'', include('oauth.urls', namespace='oauth')),
                  url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
                      name='django.contrib.sitemaps.views.sitemap'),
                  url(r'^feed/$', DjangoBlogFeed()),
                  url(r'^rss/$', DjangoBlogFeed()),
                  url(r'^search', include('haystack.urls'), name='search'),
                  url(r'', include('servermanager.urls', namespace='servermanager')),
                  url(r'', include('owntracks.urls', namespace='owntracks'))
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
#!/usr/bin/env python
# encoding: utf-8


"""
@version: ??
@author: liangliangyy
@license: MIT Licence
@contact: liangliangyy@gmail.com
@site: https://www.lylinux.net/
@software: PyCharm
@file: urls.py
@time: 2016/11/20 下午3:52
"""

from django.conf.urls import url
from django.contrib.auth import views as auth_view
from django.urls import path,re_path
from . import views
from .forms import LoginForm

app_name = "accounts"

urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(success_url='/'), name='login', kwargs={'authentication_form': LoginForm}),
    url(r'^register/$', views.RegisterView.as_view(success_url="/"), name='register'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    path(r'account/result.html', views.account_result, name='result'),
]

blog/urls.py
#!/usr/bin/env python
# encoding: utf-8


"""
@version: ??
@author: liangliangyy
@license: MIT Licence
@contact: liangliangyy@gmail.com
@site: https://www.lylinux.net/
@software: PyCharm
@file: urls.py
@time: 2016/11/2 下午7:15
"""

from django.urls import path
from django.views.decorators.cache import cache_page
from . import views
from haystack.forms import ModelSearchForm
from haystack.query import SearchQuerySet
from haystack.views import SearchView

app_name = "blog"
urlpatterns = [
    path(r'', views.IndexView.as_view(), name='index'),
    path(r'page/<int:page>/', views.IndexView.as_view(), name='index_page'), #请求到ListView的父类BaseListView里的get(),kwargs={'page': 1}

    path(r'article/<int:year>/<int:month>/<int:day>/<int:article_id>.html',
#     path(r'article/<int:article_id>.html',
         views.ArticleDetailView.as_view(),
         name='detailbyid'),

    path(r'category/<slug:category_name>.html', views.CategoryDetailView.as_view(), name='category_detail'),
    path(r'category/<slug:category_name>/<int:page>.html', views.CategoryDetailView.as_view(),
         name='category_detail_page'),

    path(r'author/<author_name>.html', views.AuthorDetailView.as_view(), name='author_detail'),
    path(r'author/<author_name>/<int:page>.html', views.AuthorDetailView.as_view(),
         name='author_detail_page'),

    path(r'tag/<slug:tag_name>.html', views.TagDetailView.as_view(), name='tag_detail'),
    path(r'tag/<slug:tag_name>/<int:page>.html', views.TagDetailView.as_view(), name='tag_detail_page'),
    path('archives.html', cache_page(60 * 60)(views.ArchivesView.as_view()), name='archives'),
    path('links.html', views.LinkListView.as_view(), name='links'),
    path(r'upload', views.fileupload, name='upload'),
    path(r'refresh', views.refresh_memcache, name='refresh')

]

owntracks/urls.py
#!/usr/bin/env python
# encoding: utf-8


"""
@version: ??
@author: liangliangyy
@license: MIT Licence 
@contact: liangliangyy@gmail.com
@site: https://www.lylinux.net/
@software: PyCharm
@file: urls.py
@time: 2018/2/25 下午3:04
"""
from django.urls import path
from . import views

app_name = "owntracks"

urlpatterns = [
    path('owntracks/logtracks', views.manage_owntrack_log, name='logtracks'),
    path('owntracks/show_maps', views.show_maps, name='show_maps'),
    path('owntracks/get_datas', views.get_datas, name='get_datas'),
    path('owntracks/show_dates', views.show_log_dates, name='show_dates')
]

comments/models.py
from django.db import models
from django.conf import settings
from blog.models import Article
from django.utils.timezone import now


# Create your models here.

class Comment(models.Model):
    body = models.TextField('正文', max_length=300)
    created_time = models.DateTimeField('创建时间', default=now)
    last_mod_time = models.DateTimeField('修改时间', default=now)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='作者', on_delete=models.CASCADE)
    article = models.ForeignKey(Article, verbose_name='文章', on_delete=models.CASCADE)
    parent_comment = models.ForeignKey('self', verbose_name="上级评论", blank=True, null=True, on_delete=models.CASCADE)
    is_enable = models.BooleanField('是否显示', default=True, blank=False, null=False)

    class Meta:
        ordering = ['id']
        verbose_name = "评论"
        verbose_name_plural = verbose_name
        get_latest_by = 'id'

    def __str__(self):
        return self.body

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

blog/forms.py
#!/usr/bin/env python
# encoding: utf-8


"""
@version: ??
@author: liangliangyy
@license: MIT Licence 
@contact: liangliangyy@gmail.com
@site: https://www.lylinux.net/
@software: PyCharm
@file: forms.py
@time: 2017/1/7 上午12:36
"""

from haystack.forms import SearchForm
from django import forms
import logging

logger = logging.getLogger(__name__)


class BlogSearchForm(SearchForm):
    querydata = forms.CharField(required=True)

    def search(self):
        datas = super(BlogSearchForm, self).search()
        if not self.is_valid():
            return self.no_query_found()

        if self.cleaned_data['querydata']:
            logger.info(self.cleaned_data['querydata'])
        return datas

blog/views.py
from django.shortcuts import render

# Create your views here.
import os
import datetime
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.conf import settings
from django import forms
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from DjangoBlog.utils import cache, get_md5, get_blog_setting
from django.shortcuts import get_object_or_404
from blog.models import Article, Category, Tag, Links
from comments.forms import CommentForm
import logging

logger = logging.getLogger(__name__)


class ArticleListView(ListView):
    # template_name属性用于指定使用哪个模板进行渲染
    template_name = 'blog/article_index.html'

    # context_object_name属性用于给上下文变量取名（在模板中使用该名字）
    context_object_name = 'article_list'

    # 页面类型，分类目录或标签列表等
    page_type = ''
    # paginate_by = settings.PAGINATE_BY
    paginate_by = 4
    page_kwarg = 'page'   #重写了父类的page_kwarg， 父类默认也是page
    link_type = 'l'
    model = Article

    def get_view_cache_key(self):
        logger.info(self.request)
        return self.request.get['pages']

    @property
    def page_number(self):
        page_kwarg = self.page_kwarg
        page = self.kwargs.get(page_kwarg) or self.request.GET.get(page_kwarg) or 1
        logger.info(page)
        return page

    def get_queryset_cache_key(self):  
        """
        子类重写.获得queryset的缓存key
        """
        raise NotImplementedError()   #表示子类中调用这个函数时，必须在子类里重写，否则报错

    def get_queryset_data(self):
        """
        子类重写.获取queryset的数据
        """
        raise NotImplementedError()

    def get_queryset_from_cache(self, cache_key):
        '''
        缓存页面数据
        :param cache_key: 缓存key
        :return:
        '''
        value = cache.get(cache_key)
        if value:
            logger.info('get view cache.key:{key}'.format(key=cache_key))
            return value
        else:
            article_list = self.get_queryset_data()
            cache.set(cache_key, article_list)
            logger.info('set view cache.key:{key}'.format(key=cache_key))
            return article_list

    def get_queryset(self):
        '''
        重写默认，从缓存获取数据
        :return:
        '''
        # super(ArticleListView,self).get_queryset()
        super().get_queryset()
        key = self.get_queryset_cache_key()
        value = self.get_queryset_from_cache(key)
        return value

    def get_context_data(self, **kwargs):
        kwargs['linktype'] = self.link_type
        return super(ArticleListView, self).get_context_data(**kwargs)


class IndexView(ArticleListView):
    '''
    首页
    '''
    # 友情链接类型
    link_type = 'i'

    def get_queryset_data(self):
        article_list = Article.objects.filter(type='a', status='p')
        return article_list

    def get_queryset_cache_key(self):
        cache_key = 'index_{page}'.format(page=self.page_number)
        return cache_key


class ArticleDetailView(DetailView):
    '''
    文章详情页面
    '''
    template_name = 'blog/article_detail.html'
    model = Article
    pk_url_kwarg = 'article_id'  #重写主键字段
    context_object_name = "article"

    def get_object(self, queryset=None):
        obj = super(ArticleDetailView, self).get_object()
        obj.viewed()
        self.object = obj
        return obj

    def get_context_data(self, **kwargs):
        print("ArticleDetailView.get_context_data:",kwargs)
        print("ArticleDetailView.get_context_data:",self.kwargs)
        articleid = int(self.kwargs[self.pk_url_kwarg])
        comment_form = CommentForm()
        user = self.request.user
        # 如果用户已经登录，则隐藏邮件和用户名输入框
        if user.is_authenticated and not user.is_anonymous and user.email and user.username:
            comment_form.fields.update({
                'email': forms.CharField(widget=forms.HiddenInput()),
                'name': forms.CharField(widget=forms.HiddenInput()),
            })
            comment_form.fields["email"].initial = user.email
            comment_form.fields["name"].initial = user.username

        article_comments = self.object.comment_list()

        kwargs['form'] = comment_form
        kwargs['article_comments'] = article_comments
        kwargs['comment_count'] = len(article_comments) if article_comments else 0

        kwargs['next_article'] = self.object.next_article
        kwargs['prev_article'] = self.object.prev_article

        return super(ArticleDetailView, self).get_context_data(**kwargs)


class CategoryDetailView(ArticleListView):
    '''
    分类目录列表
    '''
    page_type = "分类目录归档"

    def get_queryset_data(self):
        slug = self.kwargs['category_name']
        category = get_object_or_404(Category, slug=slug)

        categoryname = category.name
        self.categoryname = categoryname
        categorynames = list(map(lambda c: c.name, category.get_sub_categorys()))
        article_list = Article.objects.filter(category__name__in=categorynames, status='p')
        return article_list

    def get_queryset_cache_key(self):
        slug = self.kwargs['category_name']
        category = get_object_or_404(Category, slug=slug)
        categoryname = category.name
        self.categoryname = categoryname
        cache_key = 'category_list_{categoryname}_{page}'.format(categoryname=categoryname, page=self.page_number)
        return cache_key

    def get_context_data(self, **kwargs):

        categoryname = self.categoryname
        try:
            categoryname = categoryname.split('/')[-1]
        except:
            pass
        kwargs['page_type'] = CategoryDetailView.page_type
        kwargs['tag_name'] = categoryname
        return super(CategoryDetailView, self).get_context_data(**kwargs)


class AuthorDetailView(ArticleListView):
    '''
    作者详情页
    '''
    page_type = '作者文章归档'

    def get_queryset_cache_key(self):
        author_name = self.kwargs['author_name']
        cache_key = 'author_{author_name}_{page}'.format(author_name=author_name, page=self.page_number)
        return cache_key

    def get_queryset_data(self):
        author_name = self.kwargs['author_name']  #通过url拿到author_name传参
        article_list = Article.objects.filter(author__username=author_name, type='a', status='p')
        return article_list

    def get_context_data(self, **kwargs):
        author_name = self.kwargs['author_name']
        kwargs['page_type'] = AuthorDetailView.page_type
        kwargs['tag_name'] = author_name
        return super(AuthorDetailView, self).get_context_data(**kwargs)


class TagDetailView(ArticleListView):
    '''
    标签列表页面
    '''
    page_type = '分类标签归档'

    def get_queryset_data(self):
        slug = self.kwargs['tag_name']
        tag = get_object_or_404(Tag, slug=slug)
        tag_name = tag.name
        self.name = tag_name
        article_list = Article.objects.filter(tags__name=tag_name, type='a', status='p')
        return article_list

    def get_queryset_cache_key(self):
        slug = self.kwargs['tag_name']
        tag = get_object_or_404(Tag, slug=slug)
        tag_name = tag.name
        self.name = tag_name
        cache_key = 'tag_{tag_name}_{page}'.format(tag_name=tag_name, page=self.page_number)
        return cache_key

    def get_context_data(self, **kwargs):
        # tag_name = self.kwargs['tag_name']
        tag_name = self.name
        kwargs['page_type'] = TagDetailView.page_type
        kwargs['tag_name'] = tag_name
        return super(TagDetailView, self).get_context_data(**kwargs)


class ArchivesView(ArticleListView):
    '''
    文章归档页面
    '''
    page_type = '文章归档'
    paginate_by = None
    page_kwarg = None
    template_name = 'blog/article_archives.html'

    def get_queryset_data(self):
        return Article.objects.filter(status='p').all()

    def get_queryset_cache_key(self):
        cache_key = 'archives'
        return cache_key


class LinkListView(ListView):
    model = Links
    template_name = 'blog/links_list.html'

    def get_queryset(self):
        return Links.objects.filter(is_enable=True)


@csrf_exempt
def fileupload(request):
    """
    该方法需自己写调用端来上传图片，该方法仅提供图床功能
    :param request:
    :return:
    """
    if request.method == 'POST':
        sign = request.GET.get('sign', None)
        if not sign:
            return HttpResponseForbidden()
        if not sign == get_md5(get_md5(settings.SECRET_KEY)):
            return HttpResponseForbidden()
        response = []
        for filename in request.FILES:
            timestr = datetime.datetime.now().strftime('%Y/%m/%d')
            imgextensions = ['jpg', 'png', 'jpeg', 'bmp']
            fname = u''.join(str(filename))
            isimage = len([i for i in imgextensions if fname.find(i) >= 0]) > 0
            blogsetting = get_blog_setting()

            basepath = r'{basedir}/{type}/{timestr}'.format(basedir=blogsetting.resource_path,
                                                            type='files' if not isimage else 'image', timestr=timestr)
            if settings.TESTING:
                basepath = settings.BASE_DIR + '/uploads'
            url = 'https://resource.lylinux.net/{type}/{timestr}/{filename}'.format(
                type='files' if not isimage else 'image', timestr=timestr, filename=filename)
            if not os.path.exists(basepath):
                os.makedirs(basepath)
            savepath = os.path.join(basepath, filename)
            with open(savepath, 'wb+') as wfile:
                for chunk in request.FILES[filename].chunks():
                    wfile.write(chunk)
            if isimage:
                from PIL import Image
                image = Image.open(savepath)
                image.save(savepath, quality=20, optimize=True)
            response.append(url)
        return HttpResponse(response)

    else:
        return HttpResponse("only for post")


@login_required
def refresh_memcache(request):
    try:

        if request.user.is_superuser:

templates/blog/tags/article_info.html
{% load blog_tags %}
{% load cache %}
<article id="post-{{ article.pk }} "
         class="post-{{ article.pk }} post type-post status-publish format-standard hentry">
    <header class="entry-header">

        <h1 class="entry-title">
            {% if  isindex %}
                {% if article.article_order > 0 %}
                    <a href="{{ article.get_absolute_url }}"
                       rel="bookmark">【置顶】{{ article.title }}</a>
                {% else %}
                    <a href="{{ article.get_absolute_url }}"
                       rel="bookmark">{{ article.title }}</a>
                {% endif %}

            {% else %}
                {{ article.title }}
            {% endif %}
        </h1>
        <div class="comments-link">
            {% if article.comment_status == "o" and open_site_comment %}
                <a href="{{ article.get_absolute_url }}#comments" class="ds-thread-count" data-thread-key="3815"
                   rel="nofollow">
                    <span class="leave-reply">
                    {% if article.comment and article.comment_set.count %}
                        {{ article.comment_set.count }}个评论
                    {% else %}
                        发表评论
                    {% endif %}
                    </span>
                </a>
            {% endif %}
            <div style="float:right">
                {{ article.views }} views
            </div>
        </div><!-- .comments-link -->
        <br/>
        {% if article.type == 'a' %}
            {% if not isindex %}
                {% cache 36000 breadcrumb article.pk %}
                    {% load_breadcrumb article %}
                {% endcache %}
            {% endif %}
        {% endif %}
    </header><!-- .entry-header -->

    <div class="entry-content" itemprop="articleBody">
        {% if  isindex %}
            {{ article.body|custom_markdown|escape|truncatechars_content }}
            <p class='read-more'><a
                    href=' {{ article.get_absolute_url }}'>Read more</a></p>
        {% else %}
            {{ article.body|custom_markdown }}
        {% endif %}

    </div><!-- .entry-content -->

    {% load_article_metas article user %}

</article><!-- #post -->

templates/blog/tags/article_meta_info.html
{% load blog_tags %}
{% load cache %}
{% with article.id|add:user.is_authenticated as cachekey %}
    {% cache 36000 metainfo cachekey %}
        <footer class="entry-meta">
            本条目发布于<a href="{{ article.get_absolute_url }}" title="{% datetimeformat article.pub_time %}"
                     itemprop="datePublished" content="{% datetimeformat article.pub_time %}"
                     rel="bookmark">

            <time class="entry-date updated"
                  datetime="{{ article.pub_time }}">
                {% datetimeformat article.pub_time %}</time>
        </a>
            {% if article.type == 'a' %}
                。属于<a href="{{ article.category.get_absolute_url }}" rel="category tag">{{ article.category.name }}</a>
                分类，
                {% if article.tags.all %}
                    被贴了

                    {% for t in article.tags.all %}
                        <a href="{{ t.get_absolute_url }}" rel="tag">{{ t.name }}</a>
                        {% if t != article.tags.all.last %}
                            ，
                        {% endif %}
                    {% endfor %}

                    标签。
                {% endif %}
            {% endif %}
            <span class="by-author">作者是
        <span class="author vcard">
            <a class="url fn n" href="{{ article.author.get_absolute_url }}"
               title="查看所有由{{ article.author.username }}发布的文章"
               rel="author">
            <span itemprop="author" itemscope itemtype="http://schema.org/Person">

            <span itemprop="name" itemprop="publisher">

            {{ article.author.username }}
        </span>
            </span>
    </a>
        </span>。
                {% if user.is_superuser %}
                    <a href="{{ article.get_admin_url }}">编辑</a>
                {% endif %}
    </span>
        </footer><!-- .entry-meta -->

    {% endcache %}
{% endwith %}

templates/blog/tags/article_pagination.html
<nav id="nav-below" class="navigation" role="navigation">
    <h3 class="assistive-text">文章导航</h3>
    {% if page_obj.has_next  and next_url%}
        <div class="nav-previous"><a
                href="{{ next_url }}"><span
                class="meta-nav">&larr;</span> 早期文章</a></div>
    {% endif %}
    {% if page_obj.has_previous and previous_url %}
        <div class="nav-next"><a href="{{ previous_url }}">较新文章
            <span
                    class="meta-nav">→</span></a>
        </div>
    {% endif %}
</nav><!-- .navigation -->

templates/blog/tags/article_tag_list.html
{% if article_tags_list %}
    <div class="panel panel-default">
        <div class="panel-heading">标签</div>
        <div class="panel-body">

            {% for url,count,tag,color in article_tags_list %}
                <a class="label label-{{ color }}" style="display: inline-block;" href="{{ url }}"
                   title="{{ tag.name }}">
                    {{ tag.name }}
                    <span class="badge">{{ count }}</span>
                </a>
            {% endfor %}

        </div>
    </div>
{% endif %}

templates/blog/tags/breadcrumb.html
<div class="breadcrumb">
    {% for name,url in names %}
        <div itemscope itemtype="http://data-vocabulary.org/Breadcrumb">

            <a href="{{ url }}" itemprop="url">

                <span itemprop="title"> {{ name }}</span>

            </a>&nbsp;&rsaquo;

        </div>
    {% endfor %}
    {{ title }}
</div>

templates/blog/tags/sidebar.html
{% load blog_tags %}
<div id="secondary" class="widget-area" role="complementary">
    <aside id="search-2" class="widget widget_search">
        <form role="search" method="get" id="searchform" class="searchform" action="/search">
            <div>
                <label class="screen-reader-text" for="s">搜索：</label>
                <input type="text" value="" name="q" id="q"/>
                <input type="submit" id="searchsubmit" value="搜索"/>
            </div>
        </form>
    </aside>
    {% if extra_sidebars %}
        {% for sidebar in extra_sidebars %}

            <aside class="widget_text widget widget_custom_html"><h3 class="widget-title">
                {{ sidebar.name }}</h3>
                <div class="textwidget custom-html-widget">
                    {{ sidebar.content|custom_markdown }}
                </div>
            </aside>
        {% endfor %}
    {% endif %}
    {% if most_read_articles %}

        <aside id="views-4" class="widget widget_views"><h3 class="widget-title">Views</h3>
            <ul>
                {% for a in most_read_articles %}
                    <li>
                        <a href="{{ a.get_absolute_url }}" title="{{ a.title }}">
                            {{ a.title }}
                        </a> - {{ a.views }} views
                    </li>
                {% endfor %}
            </ul>

        </aside>
    {% endif %}
    {% if sidebar_categorys %}
        <aside id="su_siloed_terms-2" class="widget widget_su_siloed_terms"><h3 class="widget-title">分类目录</h3>
            <ul>
                {% for c in sidebar_categorys %}
                    <li class="cat-item cat-item-184"><a href={{ c.get_absolute_url }}>{{ c.name }}</a>
                    </li>
                {% endfor %}
            </ul>
        </aside>
    {% endif %}
    {% if sidebar_comments and  open_site_comment %}
        <aside id="ds-recent-comments-4" class="widget ds-widget-recent-comments"><h3 class="widget-title">近期评论</h3>
            {% comment %}<ul class="ds-recent-comments" data-num-items="5" data-show-avatars="1" data-show-time="1"
            data-show-title="1" data-show-admin="1" data-avatar-size="30" data-excerpt-length="70"></ul>{% endcomment %}
            <ul id="recentcomments">
                {% for c in sidebar_comments %}
                    <li class="recentcomments">
                <span class="comment-author-link">
                    {{ c.author.username }}</span>
                        发表在《
                        <a href="{{ c.article.get_absolute_url }}#comment-{{ c.pk }}">{{ c.article.title }}</a>》
                    </li>
                {% endfor %}
            </ul>
        </aside>
    {% endif %}
    {% if recent_articles %}
        <aside id="recent-posts-2" class="widget widget_recent_entries"><h3 class="widget-title">近期文章</h3>
            <ul>

                {% for a in  recent_articles %}
                    <li><a href="{{ a.get_absolute_url }}" title="{{ a.title }}">
                        {{ a.title }}
                    </a></li>
                {% endfor %}
            </ul>
        </aside>
    {% endif %}
    {% if sidabar_links %}
        <aside id="linkcat-0" class="widget widget_links"><h3 class="widget-title">书签</h3>
            <ul class='xoxo blogroll'>
                {% for l in sidabar_links %}
                    <li>
                        <a href="{{ l.link }}" target="_blank" title="{{ l.name }}">{{ l.name }}</a>
                    </li>
                {% endfor %}

            </ul>
        </aside>
    {% endif %}
    {% if show_google_adsense %}
        <aside id="text-2" class="widget widget_text"><h3 class="widget-title">Google AdSense</h3>
            <div class="textwidget">
                {{ google_adsense_codes|safe }}
            </div>
        </aside>
    {% endif %}
    {% if sidebar_tags %}
        <aside id="tag_cloud-2" class="widget widget_tag_cloud"><h3 class="widget-title">标签云</h3>
            <div class="tagcloud">
                {% for tag,count,size in sidebar_tags %}
                    <a href="{{ tag.get_absolute_url }}"
                       class="tag-link-{{ tag.id }} tag-link-position-{{ tag.id }}"
                       style="font-size: {{ size }}pt;" title="{{ count }}个话题"> {{ tag.name }}
                    </a>
                {% endfor %}
            </div>
        </aside>
    {% endif %}
    <aside id="text-2" class="widget widget_text"><h3 class="widget-title">欢迎您star或者fork本站源代码</h3>
        <div class="textwidget">

            <p><a href="https://github.com/liangliangyy/DjangoBlog" rel="nofollow"><img
                    src="https://resource.lylinux.net/img.shields.io/github/stars/liangliangyy/djangoblog.svg?style=social&amp;label=Star"
                    alt="GitHub stars"></a> <a href="https://github.com/liangliangyy/DjangoBlog" rel="nofollow"><img
                    src="https://resource.lylinux.net/img.shields.io/github/forks/liangliangyy/djangoblog.svg?style=social&amp;label=Fork"
                    alt="GitHub forks"></a></p>
        </div>
    </aside>
    <aside id="meta-2" class="widget widget_meta"><h3 class="widget-title">功能</h3>
        <ul>
            <li><a href="/admin/" rel="nofollow">管理站点</a></li>
            {% if user.is_authenticated %}
                <li><a href="{% url "account:logout" %}" rel="nofollow">登出</a>
                </li>

            {% else %}
                <li><a href="{% url "account:login" %}" rel="nofollow">登录</a>
            {% endif %}
            {% if user.is_superuser %}
                <li><a href="{% url "blog:refresh" %}" target="_blank">刷新缓存</a></li>
                <li><a href="{% url 'owntracks:show_dates' %}" target="_blank">运动轨迹记录</a></li>
            {% endif %}
            <li><a href="http://gitbook.lylinux.net" target="_blank" rel="nofollow">GitBook</a></li>
        </ul>
    </aside>
    <div id="rocket" class="show" title="点我返回顶部"></div>
</div><!-- #secondary -->