DjangoBlog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from DjangoBlog.sitemap import StaticViewSitemap, ArticleSiteMap, CategorySiteMap, TagSiteMap, UserSiteMap
from DjangoBlog.feeds import DjangoBlogFeed
from django.views.decorators.cache import cache_page
from django.conf import settings
from django.conf.urls.static import static   #注意导包,多个static 
from DjangoBlog.admin_site import admin_site
from django.urls import include, path

sitemaps = {

    'blog': ArticleSiteMap,
    'Category': CategorySiteMap,
    'Tag': TagSiteMap,
    'User': UserSiteMap,
    'static': StaticViewSitemap
}

handler404 = 'blog.views.page_not_found_view'
handler500 = 'blog.views.server_error_view'
handle403 = 'blog.views.permission_denied_view'
urlpatterns = [
                  url(r'^admin/', admin_site.urls),
                  url(r'', include('blog.urls', namespace='blog')),
                  url(r'mdeditor/', include('mdeditor.urls')),
                  url(r'', include('comments.urls', namespace='comment')),
                  url(r'', include('accounts.urls', namespace='account')),
                  url(r'', include('oauth.urls', namespace='oauth')),
                  url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
                      name='django.contrib.sitemaps.views.sitemap'),
                  url(r'^feed/$', DjangoBlogFeed()),
                  url(r'^rss/$', DjangoBlogFeed()),
                  url(r'^search', include('haystack.urls'), name='search'),
                  url(r'', include('servermanager.urls', namespace='servermanager')),
                  url(r'', include('owntracks.urls', namespace='owntracks'))
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
#!/usr/bin/env python
# encoding: utf-8


"""
@version: ??
@author: liangliangyy
@license: MIT Licence
@contact: liangliangyy@gmail.com
@site: https://www.lylinux.net/
@software: PyCharm
@file: urls.py
@time: 2016/11/20 下午3:52
"""

from django.conf.urls import url
from django.contrib.auth import views as auth_view
from django.urls import path,re_path
from . import views
from .forms import LoginForm

app_name = "accounts"

urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(success_url='/'), name='login', kwargs={'authentication_form': LoginForm}),
    url(r'^register/$', views.RegisterView.as_view(success_url="/"), name='register'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    path(r'account/result.html', views.account_result, name='result'),
]

blog/urls.py
#!/usr/bin/env python
# encoding: utf-8


"""
@version: ??
@author: liangliangyy
@license: MIT Licence
@contact: liangliangyy@gmail.com
@site: https://www.lylinux.net/
@software: PyCharm
@file: urls.py
@time: 2016/11/2 下午7:15
"""

from django.urls import path
from django.views.decorators.cache import cache_page
from . import views
from haystack.forms import ModelSearchForm
from haystack.query import SearchQuerySet
from haystack.views import SearchView

app_name = "blog"
urlpatterns = [
    path(r'', views.IndexView.as_view(), name='index'),
    path(r'page/<int:page>/', views.IndexView.as_view(), name='index_page'), #请求到ListView的父类BaseListView里的get(),kwargs={'page': 1}

    path(r'article/<int:year>/<int:month>/<int:day>/<int:article_id>.html',
#     path(r'article/<int:article_id>.html',
         views.ArticleDetailView.as_view(),
         name='detailbyid'),

    path(r'category/<slug:category_name>.html', views.CategoryDetailView.as_view(), name='category_detail'),
    path(r'category/<slug:category_name>/<int:page>.html', views.CategoryDetailView.as_view(),
         name='category_detail_page'),

    path(r'author/<author_name>.html', views.AuthorDetailView.as_view(), name='author_detail'),
    path(r'author/<author_name>/<int:page>.html', views.AuthorDetailView.as_view(),
         name='author_detail_page'),

    path(r'tag/<slug:tag_name>.html', views.TagDetailView.as_view(), name='tag_detail'),
    path(r'tag/<slug:tag_name>/<int:page>.html', views.TagDetailView.as_view(), name='tag_detail_page'),
    path('archives.html', cache_page(60 * 60)(views.ArchivesView.as_view()), name='archives'),
    path('links.html', views.LinkListView.as_view(), name='links'),
    path(r'upload', views.fileupload, name='upload'),
    path(r'refresh', views.refresh_memcache, name='refresh')

]

blog/models.py
import logging
from abc import ABCMeta, abstractmethod, abstractproperty

from django.db import models
from django.urls import reverse
from django.conf import settings
from uuslug import slugify
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from DjangoBlog.utils import get_current_site
from DjangoBlog.utils import cache_decorator, cache
from django.utils.timezone import now
from mdeditor.fields import MDTextField  

logger = logging.getLogger(__name__)

LINK_SHOW_TYPE = (
    ('i', '首页'),
    ('l', '列表页'),
    ('p', '文章页面'),
    ('a', '全站'),
    ('s', '友情链接页面'),
)


class BaseModel(models.Model):
    id = models.AutoField(primary_key=True)
    created_time = models.DateTimeField('创建时间', default=now)
    last_mod_time = models.DateTimeField('修改时间', default=now)

    def save(self, *args, **kwargs):
        is_update_views = isinstance(self, Article) and 'update_fields' in kwargs and kwargs['update_fields'] == [
            'views']
        if is_update_views:
            Article.objects.filter(pk=self.pk).update(views=self.views)
        else:
            if 'slug' in self.__dict__:
                slug = getattr(self, 'title') if 'title' in self.__dict__ else getattr(self, 'name')
                setattr(self, 'slug', slugify(slug))
            super().save(*args, **kwargs)

    def get_full_url(self):
        site = get_current_site().domain
        url = "https://{site}{path}".format(site=site, path=self.get_absolute_url())
        return url

    class Meta:
        abstract = True

    @abstractmethod
    def get_absolute_url(self):
        pass


class Article(BaseModel):
    """文章"""
    STATUS_CHOICES = (
        ('d', '草稿'),
        ('p', '发表'),
    )
    COMMENT_STATUS = (
        ('o', '打开'),
        ('c', '关闭'),
    )
    TYPE = (
        ('a', '文章'),
        ('p', '页面'),
    )
    title = models.CharField('标题', max_length=200, unique=True)
    # body = MDTextField('正文')
    body = models.TextField('正文')
    pub_time = models.DateTimeField('发布时间', blank=False, null=False, default=now)
    status = models.CharField('文章状态', max_length=1, choices=STATUS_CHOICES, default='p')
    comment_status = models.CharField('评论状态', max_length=1, choices=COMMENT_STATUS, default='o')
    type = models.CharField('类型', max_length=1, choices=TYPE, default='a')
    views = models.PositiveIntegerField('浏览量', default=0)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='作者', blank=False, null=False,
                               on_delete=models.CASCADE)
    article_order = models.IntegerField('排序,数字越大越靠前', blank=False, null=False, default=0)
    category = models.ForeignKey('Category', verbose_name='分类', on_delete=models.CASCADE, blank=False, null=False)
    tags = models.ManyToManyField('Tag', verbose_name='标签集合', blank=True)

    def body_to_string(self):
        return self.body

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-article_order', '-pub_time']
        verbose_name = "文章"
        verbose_name_plural = verbose_name
        get_latest_by = 'id'

    def get_absolute_url(self):
        return reverse('blog:detailbyid', kwargs={ #反转找到path(r'article/<int:year>/<int:month>/<int:day>/<int:article_id>.html',，
            'article_id': self.id,               #path里的参数要与reverse里对应，多了少了都会报错
            'year': self.created_time.year,
            'month': self.created_time.month,
            'day': self.created_time.day
        })

    @cache_decorator(60 * 60 * 10)
    def get_category_tree(self):
        print("blog.models.Article.get_category_tree.缓存方法")
        tree = self.category.get_category_tree()
        names = list(map(lambda c: (c.name, c.get_absolute_url()), tree))
        return names

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

    def viewed(self):
        self.views += 1
        self.save(update_fields=['views'])

    def comment_list(self):
        cache_key = 'article_comments_{id}'.format(id=self.id)
        value = cache.get(cache_key)
        if value:
            logger.info('get article comments:{id}'.format(id=self.id))
            return value
        else:
            comments = self.comment_set.filter(is_enable=True)
            cache.set(cache_key, comments, 60 * 100)
            logger.info('set article comments:{id}'.format(id=self.id))
            return comments

    def get_admin_url(self):
        info = (self._meta.app_label, self._meta.model_name)
        return reverse('admin:%s_%s_change' % info, args=(self.pk,))

    @cache_decorator(expiration=60 * 100)
    def next_article(self):
        print("blog.models.Article.next_article.缓存方法")
        # 下一篇
        return Article.objects.filter(id__gt=self.id, status='p').order_by('id').first()

    @cache_decorator(expiration=60 * 100)  #expiration 到期
    def prev_article(self):
        print("blog.models.Article.prev_article.缓存方法")
        # 前一篇
        return Article.objects.filter(id__lt=self.id, status='p').first()


class Category(BaseModel):
    """文章分类"""
    name = models.CharField('分类名', max_length=30, unique=True)
    parent_category = models.ForeignKey('self', verbose_name="父级分类", blank=True, null=True, on_delete=models.CASCADE)
    slug = models.SlugField(default='no-slug', max_length=60, blank=True)

    class Meta:
        ordering = ['name']
        verbose_name = "分类"
        verbose_name_plural = verbose_name

    def get_absolute_url(self):
        return reverse('blog:category_detail', kwargs={'category_name': self.slug})

    def __str__(self):
        return self.name

    @cache_decorator(60 * 60 * 10)
    def get_category_tree(self):
        """
        递归获得分类目录的父级
        :return: 
        """
        categorys = []

        def parse(category):
            categorys.append(category)
            if category.parent_category:
                parse(category.parent_category)

        parse(self)
        return categorys

    @cache_decorator(60 * 60 * 10)
    def get_sub_categorys(self):
        """
        获得当前分类目录所有子集
        :return: 
        """
        categorys = []
        all_categorys = Category.objects.all()

        def parse(category):
            if category not in categorys:
                categorys.append(category)
            childs = all_categorys.filter(parent_category=category)
            for child in childs:
                if category not in categorys:
                    categorys.append(child)
                parse(child)

        parse(self)
        return categorys


class Tag(BaseModel):
    """文章标签"""
    name = models.CharField('标签名', max_length=30, unique=True)
    slug = models.SlugField(default='no-slug', max_length=60, blank=True) #后面用exclude排出admin可以编辑区域

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:tag_detail', kwargs={'tag_name': self.slug})

    @cache_decorator(60 * 60 * 10)
    def get_article_count(self):
        return Article.objects.filter(tags__name=self.name).distinct().count()

    class Meta:
        ordering = ['name']
        verbose_name = "标签"
        verbose_name_plural = verbose_name


class Links(models.Model):
    """友情链接"""

    name = models.CharField('链接名称', max_length=30, unique=True)
    link = models.URLField('链接地址')
    sequence = models.IntegerField('排序', unique=True)
    is_enable = models.BooleanField('是否显示', default=True, blank=False, null=False)
    show_type = models.CharField('显示类型', max_length=1, choices=LINK_SHOW_TYPE, default='i')
    created_time = models.DateTimeField('创建时间', default=now)
    last_mod_time = models.DateTimeField('修改时间', default=now)

    class Meta:
        ordering = ['sequence']
        verbose_name = '友情链接'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class SideBar(models.Model):
    """侧边栏,可以展示一些html内容"""
    name = models.CharField('标题', max_length=100)
    content = models.TextField("内容")
    sequence = models.IntegerField('排序', unique=True)
    is_enable = models.BooleanField('是否启用', default=True)
    created_time = models.DateTimeField('创建时间', default=now)
    last_mod_time = models.DateTimeField('修改时间', default=now)

    class Meta:
        ordering = ['sequence']
        verbose_name = '侧边栏'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class BlogSettings(models.Model):
    '''站点设置 '''
    sitename = models.CharField("网站名称", max_length=200, null=False, blank=False, default='')
    site_description = models.TextField("网站描述", max_length=1000, null=False, blank=False, default='')
    site_seo_description = models.TextField("网站SEO描述", max_length=1000, null=False, blank=False, default='')
    site_keywords = models.TextField("网站关键字", max_length=1000, null=False, blank=False, default='')
    article_sub_length = models.IntegerField("文章摘要长度", default=300)
    sidebar_article_count = models.IntegerField("侧边栏文章数目", default=10)
    sidebar_comment_count = models.IntegerField("侧边栏评论数目", default=5)
    show_google_adsense = models.BooleanField('是否显示谷歌广告', default=False)
    google_adsense_codes = models.TextField('广告内容', max_length=2000, null=True, blank=True, default='')
    open_site_comment = models.BooleanField('是否打开网站评论功能', default=True)
    beiancode = models.CharField('备案号', max_length=2000, null=True, blank=True, default='')
    analyticscode = models.TextField("网站统计代码", max_length=1000, null=False, blank=False, default='')
    show_gongan_code = models.BooleanField('是否显示公安备案号', default=False, null=False)
    gongan_beiancode = models.TextField('公安备案号', max_length=2000, null=True, blank=True, default='')
    resource_path = models.CharField("静态文件保存地址", max_length=300, null=False, default='/var/www/resource/')

    class Meta:
        verbose_name = '网站配置'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.sitename

    def clean(self):   #当add实例时，先执行clean，再执行save

blog/forms.py
#!/usr/bin/env python
# encoding: utf-8


"""
@version: ??
@author: liangliangyy
@license: MIT Licence 
@contact: liangliangyy@gmail.com
@site: https://www.lylinux.net/
@software: PyCharm
@file: forms.py
@time: 2017/1/7 上午12:36
"""

from haystack.forms import SearchForm
from django import forms
import logging

logger = logging.getLogger(__name__)


class BlogSearchForm(SearchForm):
    querydata = forms.CharField(required=True)

    def search(self):
        datas = super(BlogSearchForm, self).search()
        if not self.is_valid():
            return self.no_query_found()

        if self.cleaned_data['querydata']:
            logger.info(self.cleaned_data['querydata'])
        return datas

templates/blog/article_archives.html
{% extends 'share_layout/base.html' %}
{% load blog_tags %}
{% load cache %}
{% block header %}

    <title>文章归档 | {{ SITE_DESCRIPTION }}</title>

    <meta name="description" content="{{ SITE_SEO_DESCRIPTION }}"/>
    <meta name="keywords" content="{{ SITE_KEYWORDS }}"/>
    <meta property="og:type" content="blog"/>
    <meta property="og:title" content="{{ SITE_NAME }}"/>
    <meta property="og:description" content="{{ SITE_DESCRIPTION }}"/>
    <meta property="og:url" content="{{ SITE_BASE_URL }}"/>
    <meta property="og:site_name" content="{{ SITE_NAME }}"/>

{% endblock %}
{% block content %}
    <div id="primary" class="site-content">
        <div id="content" role="main">

            <header class="archive-header">

                <p class="archive-title">文章归档</p>
            </header><!-- .archive-header -->

            <div class="entry-content">

                {% regroup article_list by pub_time.year as year_post_group %}
                <ul>
                    {% for year in year_post_group %}
                        <li>{{ year.grouper }} 年
                            {% regroup year.list by pub_time.month as month_post_group %}
                            <ul>
                                {% for month in month_post_group %}
                                    <li>{{ month.grouper }} 月
                                        <ul>
                                            {% for article in month.list %}
                                                <li><a href="{{ article.get_absolute_url }}">{{ article.title }}</a>
                                                </li>
                                            {% endfor %}
                                        </ul>
                                    </li>
                                {% endfor %}
                            </ul>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div><!-- #content -->
    </div><!-- #primary -->

{% endblock %}


{% block sidebar %}
    {% load_sidebar user 'i' %}
{% endblock %}

templates/blog/article_detail.html
{% extends 'share_layout/base.html' %}
{% load blog_tags %}
{% load cache %}
{% block header %}
    <title>{{ article.title }} | {{ SITE_DESCRIPTION }}</title>
    <meta property="og:type" content="article"/>
    <meta property="og:title" content="{{ article.title }}"/>


    <meta property="og:description" content="{{ article.body|custom_markdown|striptags|truncatewords:1 }}"/>
    <meta property="og:url"
          content="{{ article.get_full_url }}"/>
    <meta property="article:published_time" content="{% datetimeformat article.pub_time %}"/>
    <meta property="article:modified_time" content="{% datetimeformat article.pub_time %}"/>
    <meta property="article:author" content="{{ article.author.get_full_url }}"/>
    <meta property="article:section" content="{{ article.category.name }}"/>
    {% for t in article.tags.all %}
        <meta property="article:tag" content="{{ t.name }}"/>
    {% endfor %}
    <meta property="og:site_name" content="{{ SITE_NAME }}"/>

    <meta name="description" content="{{ article.body|custom_markdown|striptags|truncatewords:1 }}"/>
    {% if article.tags %}
        <meta name="keywords" content="{{ article.tags.all|join:"," }}"/>
    {% else %}
        <meta name="keywords" content="{{ SITE_KEYWORDS }}"/>
    {% endif %}

{% endblock %}
{% block content %}
    <div id="primary" class="site-content">
        <div id="content" role="main">
            {% load_article_detail article False user %}

            {% if article.type == 'a' %}
                <nav class="nav-single">
                    <h3 class="assistive-text">文章导航</h3>
                    {% if next_article %} -->

                        <span class="nav-previous"><a href="{{ next_article.get_absolute_url }}" rel="prev"><span>
                                class="meta-nav">&larr;</span> {{ next_article.title }}</a></span>
                    {% endif %}
                    {% if prev_article %}
                        <span class="nav-next"><a href="{{ prev_article.get_absolute_url }}"
                                                  rel="next">{{ prev_article.title }} <span
                                class="meta-nav">&rarr;</span></a></span>
                    {% endif %}
                </nav><!-- .nav-single
            {% endif %}

        </div><!-- #content -->
        {% if article.comment_status == "o" and OPEN_SITE_COMMENT %}


            {% include 'comments/tags/comment_list.html' %}
            {% if user.is_authenticated %}
                {% include 'comments/tags/post_comment.html' %}
            {% else %}
                <div class="comments-area">
                    <h3 class="comment-meta">您还没有登录，请您<a
                            href="{% url "account:login" %}?next={{ request.get_full_path }}" rel="nofollow">登录</a>后发表评论。
                    </h3>

                    {% load oauth_tags %}
                    {% load_oauth_applications request %}

                </div>
            {% endif %}
        {% endif %}
    </div><!-- #primary -->

{% endblock %}

{% block sidebar %}
    {% with request.user.username|add:'p' as cachekey %}
        {% cache 36000 sidebar cachekey %}
            {% load_sidebar user 'p' %}
        {% endcache %}
    {% endwith %}
{% endblock %}

templates/blog/article_index.html
{% extends 'share_layout/base.html' %}
{% load blog_tags %}
{% load cache %}
{% block header %}
    {% if tag_name %}
        <title>{{ page_type }}:{{ tag_name }} | {{ SITE_DESCRIPTION }}</title>
        {% comment %}<meta name="description" content="{{ page_type }}:{{ tag_name }}"/>{% endcomment %}
    {% else %}
        <title>{{ SITE_NAME }} | {{ SITE_DESCRIPTION }}</title>
    {% endif %}
    <meta name="description" content="{{ SITE_SEO_DESCRIPTION }}"/>
    <meta name="keywords" content="{{ SITE_KEYWORDS }}"/>
    <meta property="og:type" content="blog"/>
    <meta property="og:title" content="{{ SITE_NAME }}"/>
    <meta property="og:description" content="{{ SITE_DESCRIPTION }}"/>
    <meta property="og:url" content="{{ SITE_BASE_URL }}"/>
    <meta property="og:site_name" content="{{ SITE_NAME }}"/>
{% endblock %}
{% block content %}
    <div id="primary" class="site-content">
        <div id="content" role="main">
            article_index111111111111111111111111
            {% if page_type and tag_name %}
                <header class="archive-header">

                    <p class="archive-title">{{ page_type }}：<span>{{ tag_name }}</span></p>
                </header><!-- .archive-header -->
            {% endif %}

            {% for article in article_list %}
                {% load_article_detail article True user %}
            {% endfor %}
            {% if is_paginated %}
                {% load_pagination_info page_obj page_type tag_name %}

            {% endif %}
        </div><!-- #content -->
    </div><!-- #primary -->

{% endblock %}
{% block sidebar %}
    {% with request.user.username|add:linktype as cachekey %}
        {% cache 36000 sidebar cachekey %}
            {% load_sidebar user linktype %}
        {% endcache %}
    {% endwith %}
{% endblock %}

templates/blog/error_page.html
{% extends 'share_layout/base.html' %}
{% load blog_tags %}
{% load cache %}
{% block header %}
    {% if tag_name %}
        {% if statuscode == '404' %}
            <title>404 NotFound</title>
        {% elif statuscode == '403' %}
            <title>Permission Denied</title>
        {% elif statuscode == '500' %}
            <title>500 Error</title>
        {% else %}
            <title></title>
        {% endif %}
        {% comment %}<meta name="description" content="{{ page_type }}:{{ tag_name }}"/>{% endcomment %}
    {% else %}
        <title>{{ SITE_NAME }} | {{ SITE_DESCRIPTION }}</title>
    {% endif %}
    <meta name="description" content="{{ SITE_SEO_DESCRIPTION }}"/>
    <meta name="keywords" content="{{ SITE_KEYWORDS }}"/>
    <meta property="og:type" content="blog"/>
    <meta property="og:title" content="{{ SITE_NAME }}"/>
    <meta property="og:description" content="{{ SITE_DESCRIPTION }}"/>
    <meta property="og:url" content="{{ SITE_BASE_URL }}"/>
    <meta property="og:site_name" content="{{ SITE_NAME }}"/>
{% endblock %}
{% block content %}
    <div id="primary" class="site-content">
        <div id="content" role="main">

            <header class="archive-header">
                <h1 class="archive-title">{{ message }}</h1>
            </header><!-- .archive-header -->

        </div><!-- #content -->
    </div><!-- #primary -->

{% endblock %}


{% block sidebar %}
    {% load_sidebar user 'i' %}
{% endblock %}

templates/blog/links_list.html
{% extends 'share_layout/base.html' %}
{% load blog_tags %}
{% load cache %}
{% block header %}

    <title>友情链接 | {{ SITE_DESCRIPTION }}</title>

    <meta name="description" content="{{ SITE_SEO_DESCRIPTION }}"/>
    <meta name="keywords" content="{{ SITE_KEYWORDS }}"/>
    <meta property="og:type" content="blog"/>
    <meta property="og:title" content="{{ SITE_NAME }}"/>
    <meta property="og:description" content="{{ SITE_DESCRIPTION }}"/>
    <meta property="og:url" content="{{ SITE_BASE_URL }}"/>
    <meta property="og:site_name" content="{{ SITE_NAME }}"/>

{% endblock %}
{% block content %}
    <div id="primary" class="site-content">
        <div id="content" role="main">

            <header class="archive-header">

                <p class="archive-title">友情链接</p>
            </header><!-- .archive-header -->

            <div class="entry-content">
                <ul>
                    {% for obj in object_list %}
                        <li>
                            <a href="{{ obj.link }}">{{ obj.name }}</a>
                        </li>
                    {% endfor %} </ul>
            </div>
        </div><!-- #content -->
    </div><!-- #primary -->

{% endblock %}


{% block sidebar %}
    {% load_sidebar user 'i' %}
{% endblock %}